In [13]:
import tensorflow as tf

In [ ]:
#and gate

In [14]:
t,f=1.,-1.
bias=1.
train_in=[[t,t,bias],[t,f,bias],[f,t,bias],[f,f,bias]]
train_out=[[t],[f],[f],[f]]

In [15]:
w=tf.Variable(tf.random_normal([3,1]))

In [16]:
def step(x):
    is_greater=tf.greater(x,0)
    as_float=tf.to_float(is_greater)
    doubled=tf.multiply(as_float,2)
    return tf.subtract(doubled,1)

In [17]:
output=step(tf.matmul(train_in,w))
error=tf.subtract(train_out,output)
mse=tf.reduce_mean(tf.square(error))

In [18]:
delta=tf.matmul(train_in,error,transpose_a=True)
train=tf.assign(w,tf.add(w,delta))

In [19]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [20]:
print(train_in)

[[1.0, 1.0, 1.0], [1.0, -1.0, 1.0], [-1.0, 1.0, 1.0], [-1.0, -1.0, 1.0]]


In [21]:
x=tf.matmul(train_in,w)
print(x)
print(sess.run(x))
print(sess.run(tf.greater(x,0)))
is_great=tf.greater(x,0)
print(sess.run(tf.to_float(is_great)))
as_float=tf.to_float(is_great)
doubled=tf.multiply(as_float,2)
print(sess.run(doubled))
print(sess.run(tf.subtract(doubled,1)))

Tensor("MatMul_5:0", shape=(4, 1), dtype=float32)
[[ 4.345291  ]
 [-0.40453815]
 [ 3.1685112 ]
 [-1.581318  ]]
[[ True]
 [False]
 [ True]
 [False]]
[[1.]
 [0.]
 [1.]
 [0.]]
[[2.]
 [0.]
 [2.]
 [0.]]
[[ 1.]
 [-1.]
 [ 1.]
 [-1.]]


In [22]:
err,target=1,0
epoch,max_epochs=0,10
while err>target and epoch<(max_epochs):
    epoch+=1
    err,_=sess.run([mse,train])
    print('epoch:',epoch)
    print('mse:',err)

epoch: 1
mse: 1.0
epoch: 2
mse: 1.0
epoch: 3
mse: 0.0


In [23]:
#xor gate

In [24]:
t,f=1.,-1.
train_in=[[t,t],[t,f],[f,t],[f,f]]
train_out=[[t],[f],[f],[f]]

In [30]:
w1=tf.Variable(tf.random_normal([2,2]))
b1=tf.Variable(tf.zeros([2]))
w2=tf.Variable(tf.random_normal([2,2]))
b2=tf.Variable(tf.zeros([2]))
out1=tf.tanh(tf.add(tf.matmul(train_in,w1),b1))
out2=tf.tanh(tf.add(tf.matmul(out1,w2),b2))
error=tf.subtract(train_out,out2)
mse=tf.reduce_mean(tf.square(error))

In [36]:
sess=tf.Session()
sess.run(tf.initialize_all_variables())

In [38]:
err,target=1,0.01
epoch,max_epochs=0,10
while err>target and epoch<(max_epochs):
    epoch+=1
    err,_=sess.run([mse,train])
    print('epoch:',epoch,'mse:',err)

epoch: 1 mse: 1.1665926
epoch: 2 mse: 1.1665926
epoch: 3 mse: 1.1665926
epoch: 4 mse: 1.1665926
epoch: 5 mse: 1.1665926
epoch: 6 mse: 1.1665926
epoch: 7 mse: 1.1665926
epoch: 8 mse: 1.1665926
epoch: 9 mse: 1.1665926
epoch: 10 mse: 1.1665926
